import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { SessionProvider } from "./components/SessionProvider";
import { ScreenProvider } from "./ScreenContext";
import Layout from "./CustomLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en" className="w-screen h-screen overflow-hidden">
      <body className={inter.className}>
        <ScreenProvider>
          <Layout>
            <SessionProvider>{children}</SessionProvider>
          </Layout>
        </ScreenProvider>
      </body>
    </html>
  );
}
